title: WDL_tools的BioOS实践
lang: en
description: a catchy description for your project

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true


remote_theme: clearpathrobotics/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

