title: WDL_tools的BioOS实践
lang: en
description: a catchy description for your project


remote_theme: clearpathrobotics/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

# 添加自定义 CSS
include:
  - assets/css/prism.css
  - assets/js/prism.js

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules # new
  - vendor # new

