title: WDL_tools的BioOS实践
lang: en
description: a catchy description for your project


remote_theme: OOAAHH/jekyll-rtd-theme_as_remote


readme_index:
  with_frontmatter: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https\://github.com/jneen/rouge#full-options
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules # new
  - vendor # new

