title: WDL_tools的BioOS实践
lang: en
description: a catchy description for your project

remote_theme: OOAAHH/jekyll-rtd-theme_as_remote

readme_index:
  with_frontmatter: true
  
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock




