title: Your project name
lang: en
description: a catchy description for your project

remote_theme: clearpathrobotics/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
