source "https://rubygems.org" # source "https://gems.ruby-china.com"

gem "jekyll", "~> 4.3"
gem "jekyll-rtd-theme"  # 或者你选择的其他主题，如 jekyll-theme-primer

gem 'csv'
gem 'base64'
gem 'bigdecimal'

gem 'faraday-retry'
gem 'rubyzip', '~> 2.3', '< 3.0'

group :jekyll_plugins do
  gem "jemoji"
  gem "jekyll-avatar"
  gem "jekyll-mentions"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end
